// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARu22d3XlM2IhCEqfF4SSR3P5OqgfVeOM',
    appId: '1:647386236586:web:5e2b90715826edf232f2d3',
    messagingSenderId: '647386236586',
    projectId: 'mychat-backend-b7f4d',
    authDomain: 'mychat-backend-b7f4d.firebaseapp.com',
    storageBucket: 'mychat-backend-b7f4d.appspot.com',
    measurementId: 'G-PZL4ZG2VJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYkbE_OvWSOo7nrUQcqumsJCpGLLrruM',
    appId: '1:647386236586:android:f005c72ab1376af432f2d3',
    messagingSenderId: '647386236586',
    projectId: 'mychat-backend-b7f4d',
    storageBucket: 'mychat-backend-b7f4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGoLaJDYn9dMZX-acGwLC0XD3LbJfNHS8',
    appId: '1:647386236586:ios:f4d872ddda08e7aa32f2d3',
    messagingSenderId: '647386236586',
    projectId: 'mychat-backend-b7f4d',
    storageBucket: 'mychat-backend-b7f4d.appspot.com',
    iosBundleId: 'com.example.myChat',
  );
}
